// import { HomeModel, ItemList } from '../../model/HomeModel';
//
// class ViewHolder {
//   getItemView(item: ItemList) {
//     if (item.type == "textCard") {
//       getTextCardType(item.data.type)
//     } else {
//       getItemViewType(item.data.dataType)
//     }
//   }
// }
//
//
// let viewHolder = new ViewHolder();
//
// export default viewHolder as ViewHolder;
//
// function getTextCardType(type: any) {
//   throw new Error('Function not implemented.');
// }
//
// function getItemViewType(dataType: string) {
//   throw new Error('Function not implemented.');
// }
